test: 'test'
spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true 
  datasource:
    url: 'jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;init=create schema if not exists MCDBO'
    driverClassName: org.h2.Driver
    username: sa
    password: 
approvalservice:
  url: http://localhost:8082/v1/approval/saveCreditCard      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false


